name: model_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - azureml-defaults
    - azureml-mlflow  
    - mlflow>=2.0.0
    - joblib
    - pandas
    - scikit-learn==1.2.2
    - pyarrow
    - numpy<2.0.0