name: model_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - azureml-defaults
    - inference-schema
    - joblib
    - pandas
    - scikit-learn==1.2.2
    - pyarrow
    - mlflow
    - numpy<2.0.0